name: OnPushPaths

on:
  push:
    branches: [ main ]
    paths: [ "**.md" ]

  pull_request:
    paths-ignore: [ ".git**", "**/.keep" ]

jobs:
  on-push-paths:
    runs-on: ubuntu-latest

    steps:
      - run: echo 'executed!'
